import apoc
import matplotlib.pyplot as plt
import numpy as np
import pyclesperanto_prototype as cle
from skimage import morphology

def cilia_binarization (img):
    """
    This function binarises the cilia channel from an image array by predicting foreground and background and returns an array.
    Note: the only possible input is the cilia channel where the dimensions are the z stack and the size of the image. [:,:,:].
    Parameters:
    img: ndarray
        Variable containing the loaded image (cilia channel).
    """
    segmenter = apoc.PixelClassifier(opencl_filename='D:/estela/src/PixelClassifier.cl')
    binarized_img = segmenter.predict(image=img)
    binarized_array = np.array(binarized_img)
    plt.imshow(binarized_array[30,:,:], cmap='gray')
    
    return binarized_array

def eroder (img, radius):
    """
    This function erodes the binarised image generated by the apoc PixelClassifier and returns an array.
    Parameters:
    img: ndarray
        Variable containing the binarized image.
    """
    eroded_img = cle.erode_labels(img, radius = radius)
    eroded_array = np.array(eroded_img)
    plt.imshow(eroded_array[30,:,:], cmap='gray')
    
    return eroded_array
    
def remove_small_objects (img, min_size=64):
    """
    This function removes objects from a binarized image.
    Parameters:
    img: ndarray
        Variable containing the binarized image.
    min_size: int, optional
        The smallest allowable object size.
    """
    cleaned_img = morphology.remove_small_objects(img, min_size)
    plt.imshow(cleaned_img[30,:,:], cmap='gray')
    
    return cleaned_img